web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - .:/var/www/html
    - /var/www/html/vendor

db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: erettsegik
